name: Build Installers

on:
  push:
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]

env:
  APP_PUBLISHER: Sleepy Pandas / Anthony Hua

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Create .env
      run: echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" > src/.env
        
    - name: Build Executable
      run: |
        cd src
        go build -ldflags "-H windowsgui" -o ../figma-rpc.exe .
        
    - name: Compile Installer
      run: |
        choco install innosetup
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" scripts/installer.iss
        
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Installer
        path: dist/FigmaRPC_Setup.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Create .env
      run: echo "DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}" > src/.env
        
    - name: Build Package
      run: |
        chmod +x scripts/build_macos_pkg.sh
        ./scripts/build_macos_pkg.sh
        
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: macOS-Installer
        path: dist/FigmaRPC_Installer.pkg

  draft-release:
    needs: [ build-windows, build-macos ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Windows Installer
      uses: actions/download-artifact@v4
      with:
        name: Windows-Installer
        path: artifacts/

    - name: Download macOS Installer
      uses: actions/download-artifact@v4
      with:
        name: macOS-Installer
        path: artifacts/

    - name: Create Draft Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        generate_release_notes: true
        files: |
          artifacts/FigmaRPC_Setup.exe
          artifacts/FigmaRPC_Installer.pkg
